sudo: required
language: generic
matrix:
  include:
  - os: osx
    osx_image: xcode9.2
    language: generic
    env:
    - BUILD_CONFIG=release
    - BUILD_ARCHITECTURE=x86_64
  - os: osx
    osx_image: xcode9.2
    language: generic
    env:
    - BUILD_CONFIG=debug
    - BUILD_ARCHITECTURE=x86_64
  - os: linux
    dist: trusty
    env:
    - BUILD_CONFIG=coverage
    - BUILD_ARCHITECTURE=x86_64
    - GCC_VERSION=7
  - os: linux
    dist: trusty
    env:
    - BUILD_CONFIG=release
    - BUILD_ARCHITECTURE=x86_64
    - GCC_VERSION=7
  - os: linux
    dist: trusty
    env:
    - BUILD_CONFIG=debug
    - BUILD_ARCHITECTURE=x86_64
    - GCC_VERSION=7
  - os: linux
    dist: trusty
    env:
    - BUILD_CONFIG=release
    - BUILD_ARCHITECTURE=x86
    - GCC_VERSION=7
  - os: linux
    dist: trusty
    env:
    - BUILD_CONFIG=release
    - BUILD_ARCHITECTURE=x86_64
    - GCC_VERSION=6
  - os: linux
    dist: trusty
    env:
    - BUILD_CONFIG=debug
    - BUILD_ARCHITECTURE=x86_64
    - GCC_VERSION=6
  - os: linux
    dist: trusty
    env:
    - BUILD_CONFIG=release
    - BUILD_ARCHITECTURE=x86
    - GCC_VERSION=6
  - os: linux
    dist: trusty
    env:
    - BUILD_CONFIG=zpm
    - GCC_VERSION=6
global:
  env:
  - PROJECT=BSPLib
  - PROJECT_DIRECTORY=bsp
install:
- source /dev/stdin <<< "$(curl -s https://raw.githubusercontent.com/Zefiros-Software/ZPM/dev/script/install-zpm.sh)"
script:
- zpm run build-ci-library
after_success:
- zpm run deploy-ci-library
notifications:
  slack:
    secure: p2/koHdeVJyGte6N5ecYQIwKORdjj6V6f19X1CVulnUmhefIcsX1QHZ5rKIS7+xss4sPOvFXLN8yT9n+pRCjqEWzh927meyLINiVx19+Isl1R042m4qutmCpr0TrqsOqwJQc5HhMRusiz7tXeClhUZ6fOxZ3dGjzZmibs3jg8ntO+OSYJm2Wv9CcbR81xdYKzwGu+ujBI55QaXFuXn0QDRVl5amLYFQYb3RMSaY5ozEkmvhY5dO7Ha+zFesLmh4vlYyulWzT/wa8Pws+vuVd7Wweek1DTOIn+PQxn6JxtDKmtNthYJD8Mg8YR618NMjUUj6UvW9PozeWi+Vtja/giqHMgYrXqH7RaSDLV1S4jPexqlAQYaMJYuEcyeFWCyV783G+jkPD13x4as9gRCXqh9CMNEv7h+vQI/fLWuN4hQV1BkAWt0JEuLUZMq6zShzHOvbeueywtxlktPpEsKDk8pDqUUEenrvhx4H/eYMv4/wiIwzn+4KO4uhdm8uM4kV+Px8ipTfGSLFOieiPomSq09IbcmTj0fFGF3MlHpPaCoOJuZ1Sgt7r/CPUdzihyHr7paxYs/1QxmJKtKyJFDNkaOsrSjDyY8E6S7213vE9FQLu9MvaTeHbEOuo/u+oI4aEJjxog2Zpf1AX5XoK9BftJUhG0YbFSp31D6EY0H/m80E=
