sudo: required
language: generic
matrix:
  include:
  - os: osx
    osx_image: xcode8.3
    language: generic
    env:
    - BUILD_CONFIG=release
    - BUILD_ARCHITECTURE=x86
  - os: osx
    osx_image: xcode8.3
    language: generic
    env:
    - BUILD_CONFIG=debug
    - BUILD_ARCHITECTURE=x86
  - os: osx
    osx_image: xcode8.3
    language: generic
    env:
    - BUILD_CONFIG=release
    - BUILD_ARCHITECTURE=x86_64
  - os: osx
    osx_image: xcode8.3
    language: generic
    env:
    - BUILD_CONFIG=debug
    - BUILD_ARCHITECTURE=x86_64
  - os: linux
    dist: trusty
    env:
    - BUILD_CONFIG=coverage
    - BUILD_ARCHITECTURE=x86_64
    - GCC_VERSION=7
  - os: linux
    dist: trusty
    env:
    - BUILD_CONFIG=release
    - BUILD_ARCHITECTURE=x86_64
    - GCC_VERSION=7
  - os: linux
    dist: trusty
    env:
    - BUILD_CONFIG=debug
    - BUILD_ARCHITECTURE=x86_64
    - GCC_VERSION=7
  - os: linux
    dist: trusty
    env:
    - BUILD_CONFIG=release
    - BUILD_ARCHITECTURE=x86
    - GCC_VERSION=7
  - os: linux
    dist: trusty
    env:
    - BUILD_CONFIG=release
    - BUILD_ARCHITECTURE=x86_64
    - GCC_VERSION=6
  - os: linux
    dist: trusty
    env:
    - BUILD_CONFIG=debug
    - BUILD_ARCHITECTURE=x86_64
    - GCC_VERSION=5
  - os: linux
    dist: trusty
    env:
    - BUILD_CONFIG=release
    - BUILD_ARCHITECTURE=x86_64
    - GCC_VERSION=5
  - os: linux
    dist: trusty
    env:
    - BUILD_CONFIG=release
    - BUILD_ARCHITECTURE=x86
    - GCC_VERSION=5
  - os: linux
    dist: trusty
    env:
    - BUILD_CONFIG=zpm
    - GCC_VERSION=5
global:
  env:
  - PROJECT=BSPLib
  - PROJECT_DIRECTORY=bsp
install:
- source /dev/stdin <<< "$(curl -s https://raw.githubusercontent.com/Zefiros-Software/ZPM/features/refactor/script/install-zpm.sh)"
script:
- zpm run build-ci-library
after_success:
- zpm run deploy-ci-library
notifications:
  slack:
    secure: BDlyl/J7c3jaB+It8L4FV5LnhLlkuIRC5bEprWxc4xLlUkZTkp4h018oJI0V0u5dYKqertXgotQLqC7Tvk85VndEYp52kWyGLZ4TZkVe4w4KsrWid/zO457xUnnpQBxliF6vN79etDUoHgv39nSxD8aiYVEZJB+7+qR8Sk+IlW6JCYwkUePE0Mn/927m5nOntEVWIkJ0F9/Uo++gn6LGvbU2nujL8IztbcjGNtFLLL1bo+lZldNzafY/IBZfBBDsPma8OjVXCYeagHVXHua2ywwRgrSj+08NgzOXAqZVkjq01pk6ai+qbjgsmSsoKQUns+bybnRbecKSSQKaguxxoorFTuAjgEplmxbfumyZXucVt3mNB3Rd9+0CLkiWC3+ZCkleyRBjBnwnC+AAEMOoPX/48gCPJoz1SmXcCVUUolLZqMBaQ5oIImvuChWOUlcQzp525TgfxTTtQgM7pzZfOUTJOS81fO3T8uI52bLgI5eV4PqdhHr39aLhCQ/hLjZRDMPNV6Zy6q8p11E7kVAky5O1ORjSE3hbJDxtHVs8X65SrdQD2Jv+LWV0aB83FTqnFrNpt6x5f8NipdJmyOzY2qJ7V5bJk4xrjUCULwdPoxBlesnAJ7IzR1afPmd61RF+Rb5eqr24Tz+joC51H2aIBme9byLokiDbPY8EA1B3PEU=
