site_name: Zefiros-BSPLib
site_url: http://www.bsplib.eu
repo_url: https://github.com/Zefiros-Software/BSPLib
site_description: BSPLib a fast and easy to use parallel computation libary.
theme: united
copyright: Copyright © 2016 Mick van Duijn, Koen Visscher and Paul Visscher
google_analytics: ['UA-29999374-2', 'www.bsplib.eu']

pages:
- BSP: 
    - 'index.md'

    - Classic: 'classic.md'

- Program:
    - Logic:
        - 'Execute BSP Kernel': 'logic/execute.md'
        - 'Init BSP Kernel': 'logic/init.md'
        - 'Begin BSP Kernel': 'logic/begin.md'
        - 'End BSP Kernel': 'logic/end.md'
        
    - Halting:
        - 'Abort Program': 'halting/abort.md'

    - Util:
        - 'Processor Count': 'util/nprocs.md'
        - 'Processor Identifier': 'util/procid.md'
        - 'Wall Time': 'util/time.md'

- (De)registration:
    - 'Push Register': 'regdereg/push.md'
    - 'Pop Register': 'regdereg/pop.md'

- Communication:
    - 'Get Register':
        - 'Normal': 'com/get.md'
        - 'Primitives' : 'com/getPrimitive.md'
        - 'Pointers' : 'com/getPtrs.md'
        - 'Containers' : 'com/getContainer.md'

    - 'Put Register':
        - 'Normal': 'com/put.md'
        - 'Primitives' : 'com/putPrimitive.md'
        - 'Pointers' : 'com/putPtrs.md'
        - 'Containers' : 'com/putContainer.md'

    - Sync Point:
        - 'Synchronising': 'sync/sync.md'

- Messaging:

    - Send Memory:
        - 'Normal': 'messaging/send.md'
        - 'Primitives' : 'messaging/sendPrimitive.md'
        - 'Iterators' : 'messaging/sendIterator.md'
        - 'Containers' : 'messaging/sendContainer.md'
        - 'Pointers - Primitives' : 'messaging/sendPtrs.md'
        - 'Pointers - Containers' : 'messaging/sendTagContainer.md'
    - 'Move Memory': 'messaging/move.md'
    - 'Get Queue Size': 'messaging/qsize.md'

- Utilities:
    - 'Get Tag': 'messagingutil/gettag.md'
    - 'Set Tag Size': 'messagingutil/settagsize.md'

#- High Performance:
#    - 'Get Register': 'hp/hpget.md'
#    - 'Put Register': 'hp/hpput.md'
#    - 'Send Memory': 'hp/hpsend.md'
#    - 'Move Memory': 'hp/hpmove.md'

markdown_extensions:
    - toc:
        permalink: True
        separator: "_"
    - admonition:
    - sane_lists: